### ISSUE TITLE
 Create HTML page and Style vertically aligned appearance in styleA file

### ISSUE THREAD

**Issue by JyotikaKoneru** [JyotikaKoneru/p1#2]

**Comment by sakshiupl** [comment]
Pushed vertically aligned element changes on main branch

**Comment by Sravani1915** [comment]
Hi Sakshi, can we remove this H1 tag here: https://github.com/JyotikaKoneru/p1/blob/73c8d5d68c7e39be7e6659fa8e8ff7b5f19b5ae2/index.html#L8

**Comment by sakshiupl** [comment]
Hi Sravani,
I have removed H1 tag from index.html file

**Comment by Sravani1915** [comment]
Hey, looks good to me. Thanks!
