### ISSUE TITLE
 Create HTML page and Style horizontally aligned appearance

### ISSUE THREAD

**Issue by JyotikaKoneru** [JyotikaKoneru/p1#3]

**Comment by Sravani1915** [comment]
Hi Danish, can you please check the color here : https://github.com/JyotikaKoneru/p1/blob/73c8d5d68c7e39be7e6659fa8e8ff7b5f19b5ae2/styleB.css#L28
Let's make it black to match the requirements.

**Comment by Danish-uddin** [comment]
Done!
